# Generated by Django 4.0.6 on 2022-07-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(blank=True, max_length=250, null=True, verbose_name='FAQ Question')),
                ('faq_answer', models.TextField(blank=True, max_length=500, null=True, verbose_name='FAQ Answer')),
            ],
            options={
                'verbose_name': 'FAQ Section',
                'verbose_name_plural': 'FAQ Section',
                'db_table': 'faq_section',
            },
        ),
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=60, verbose_name='Password')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Sign Up',
                'verbose_name_plural': 'Sign Up',
                'db_table': 'sign_up',
            },
        ),
        migrations.CreateModel(
            name='Team_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=250, null=True, verbose_name="Member's Name")),
                ('member_designation', models.CharField(blank=True, max_length=250, null=True, verbose_name="Member's Designation")),
                ('member_about', models.TextField(blank=True, max_length=250, null=True, verbose_name='About Summary of Member')),
                ('member_github', models.URLField(blank=True, max_length=250, null=True, verbose_name="Member's Github Link")),
                ('member_facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name="Member's FaceBook Link")),
                ('member_linkedin', models.URLField(blank=True, max_length=250, null=True, verbose_name="Member's LinkedIn Link")),
                ('member_pic', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name="Person's Picture")),
            ],
            options={
                'verbose_name': 'Team Section',
                'verbose_name_plural': 'Team Section',
                'db_table': 'team_section',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=250, null=True, verbose_name='Person')),
                ('designation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Designation')),
                ('testimonial', models.CharField(blank=True, max_length=250, null=True, verbose_name='Testimonial')),
                ('person_link', models.URLField(blank=True, max_length=250, null=True, verbose_name="Person's Link")),
                ('person_pic', models.ImageField(blank=True, null=True, upload_to='testimonials/%Y/%m/%d/', verbose_name="Person's Picture")),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplan_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Workplan Title')),
                ('workplan_sheduled', models.DateField(blank=True, null=True, verbose_name='Scheduled At')),
                ('workplan_summary', models.TextField(blank=True, max_length=250, null=True, verbose_name='Workplan Summary')),
                ('workplan_link', models.URLField(blank=True, max_length=250, null=True, verbose_name='WorkPlan Link')),
            ],
            options={
                'verbose_name': 'Work-Plans',
                'verbose_name_plural': 'Work-Plans',
                'db_table': 'workplan',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/%y/%m/%d/')),
                ('video_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Videos', to='Capstone_App.sign_up')),
            ],
        ),
    ]
