# Generated by Django 4.0.6 on 2022-07-16 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Username')),
                ('password', models.CharField(max_length=60, verbose_name='Password')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Sign Up',
                'verbose_name_plural': 'Sign Up',
                'db_table': 'sign_up',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Person')),
                ('designation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation')),
                ('testimonial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation')),
                ('person_pic', models.ImageField(blank=True, null=True, upload_to='testimonials/%Y/%m/%d/', verbose_name='Person Pic')),
            ],
            options={
                'verbose_name': 'Testimonials',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonial',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, null=True, upload_to='%y/%m/%d/')),
                ('video_holder', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Videos', to='Capstone_App.sign_up')),
            ],
        ),
    ]
