# Generated by Django 4.0.6 on 2022-07-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='person_link',
            field=models.URLField(blank=True, null=True, verbose_name="Person's Link"),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='person_pic',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/%Y/%m/%d/', verbose_name="Person's Picture"),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Testimonial'),
        ),
    ]
