# Generated by Django 4.0.6 on 2022-07-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Upload_File',
        ),
    ]
