# Generated by Django 4.0.6 on 2022-07-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capstone_App', '0004_faq_section_alter_workplan_workplan_sheduled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, max_length=250, null=True, verbose_name="Member's Name")),
                ('member_designation', models.CharField(blank=True, max_length=250, null=True, verbose_name="Member's Designation")),
                ('member_about', models.TextField(blank=True, max_length=250, null=True, verbose_name='About Summary of Member')),
                ('member_github', models.URLField(blank=True, max_length=250, null=True, verbose_name="Member's Github Link")),
                ('member_facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name="Member's FaceBook Link")),
                ('member_linkedin', models.URLField(blank=True, max_length=250, null=True, verbose_name="Member's LinkedIn Link")),
                ('member_pic', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name="Person's Picture")),
            ],
            options={
                'verbose_name': 'Team Section',
                'verbose_name_plural': 'Team Section',
                'db_table': 'team_section',
            },
        ),
        migrations.AlterField(
            model_name='faq_section',
            name='faq_answer',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='FAQ Answer'),
        ),
    ]
